#ifndef F_ERRCODES
#define F_ERRCODES

#define PR_SUCCESS 0
#define PR_NOT_ENOUGH_MEMORY -1
#define PR_COULD_NOT_START_THREAD -2
#define PR_NO_CLIENT_WITH_SUCH_ID -3
#define PR_NO_TASK_ASSOSIATED -4
#define PR_NO_SUCH_FD_IN_THREAD -5
#define PR_CONTINUE -6

#define PR_NO_SUCH_HEADER -7
#define PR_METHOD_NOT_SUPPORTED -8
#define PR_VERSION_NOT_SUPPORTED -9
#define PR_QUERY_UNFINISHED -10

#define PR_NO_SUCH_CACHE_ENTRY -11


#endif
